/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module fsm_heldout_03(clk, rst_n, ev, state);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input clk;
  wire clk;
  wire [2:0] current_state;
  input [1:0] ev;
  wire [1:0] ev;
  wire [2:0] next_state;
  input rst_n;
  wire rst_n;
  output [2:0] state;
  wire [2:0] state;
  sky130_fd_sc_hd__nor3b_1 _11_ (
    .A(current_state[2]),
    .B(current_state[0]),
    .C_N(current_state[1]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor3b_1 _12_ (
    .A(current_state[2]),
    .B(current_state[1]),
    .C_N(current_state[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor3b_1 _13_ (
    .A(current_state[1]),
    .B(current_state[0]),
    .C_N(current_state[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__or3_1 _14_ (
    .A(_10_),
    .B(_00_),
    .C(_01_),
    .X(_02_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _15_ (
    .A(ev[1]),
    .SLEEP(_00_),
    .X(_03_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _16_ (
    .A(ev[1]),
    .SLEEP(ev[0]),
    .X(_04_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _17_ (
    .A(ev[0]),
    .SLEEP(ev[1]),
    .X(_05_)
  );
  sky130_fd_sc_hd__o31ai_1 _18_ (
    .A1(_03_),
    .A2(_04_),
    .A3(_05_),
    .B1(_02_),
    .Y(next_state[0])
  );
  sky130_fd_sc_hd__nand2_1 _19_ (
    .A(ev[0]),
    .B(_10_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o21ai_0 _20_ (
    .A1(_00_),
    .A2(_01_),
    .B1(_05_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand2_1 _21_ (
    .A(_06_),
    .B(_07_),
    .Y(next_state[1])
  );
  sky130_fd_sc_hd__nand2_1 _22_ (
    .A(ev[1]),
    .B(_01_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__o21ai_0 _23_ (
    .A1(_10_),
    .A2(_00_),
    .B1(_04_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _24_ (
    .A(_08_),
    .B(_09_),
    .Y(next_state[2])
  );
  sky130_fd_sc_hd__dfstp_2 _25_ (
    .CLK(clk),
    .D(next_state[0]),
    .Q(current_state[0]),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _26_ (
    .CLK(clk),
    .D(next_state[1]),
    .Q(current_state[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _27_ (
    .CLK(clk),
    .D(next_state[2]),
    .Q(current_state[2]),
    .RESET_B(rst_n)
  );
  assign state = current_state;
endmodule
