# Auto-generated by SiliconSignoffVerifier [config_hash: d4924eb8b36c51e0]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog fsm_heldout_03_netlist.v
link_design fsm_heldout_03
read_sdc fsm_heldout_03.sdc
report_checks
report_wns
