/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module reg_if_04(clk, rst_n, in_data, out_data);
  input clk;
  wire clk;
  input [7:0] in_data;
  wire [7:0] in_data;
  output [7:0] out_data;
  wire [7:0] out_data;
  wire [7:0] ram_reg;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__dfrtp_1 _0_ (
    .CLK(clk),
    .D(in_data[0]),
    .Q(ram_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1_ (
    .CLK(clk),
    .D(in_data[1]),
    .Q(ram_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _2_ (
    .CLK(clk),
    .D(in_data[2]),
    .Q(ram_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _3_ (
    .CLK(clk),
    .D(in_data[3]),
    .Q(ram_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(clk),
    .D(in_data[4]),
    .Q(ram_reg[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _5_ (
    .CLK(clk),
    .D(in_data[5]),
    .Q(ram_reg[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _6_ (
    .CLK(clk),
    .D(in_data[6]),
    .Q(ram_reg[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _7_ (
    .CLK(clk),
    .D(in_data[7]),
    .Q(ram_reg[7]),
    .RESET_B(rst_n)
  );
  assign out_data = ram_reg;
endmodule
