# Auto-generated by SiliconSignoffVerifier [config_hash: 7aa855b5ff8a8035]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog reg_if_04_netlist.v
link_design reg_if_04
read_sdc reg_if_04.sdc
report_checks
report_wns
