# Auto-generated by SiliconSignoffVerifier [config_hash: 5d89afbae3b52abb]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog spi_03_netlist.v
link_design spi_03
read_sdc spi_03.sdc
report_checks
report_wns
