/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module fsm_heldout_10(clk, rst_n, state_out);
  wire [1:0] _0_;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  output [1:0] state_out;
  wire [1:0] state_out;
  wire [1:0] state_reg;
  sky130_fd_sc_hd__nor2_1 _1_ (
    .A(state_reg[1]),
    .B(state_reg[0]),
    .Y(_0_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _2_ (
    .A(state_reg[0]),
    .SLEEP(state_reg[1]),
    .X(_0_[1])
  );
  sky130_fd_sc_hd__dfrtp_1 _3_ (
    .CLK(clk),
    .D(_0_[0]),
    .Q(state_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(clk),
    .D(_0_[1]),
    .Q(state_reg[1]),
    .RESET_B(rst_n)
  );
  assign state_out = state_reg;
endmodule
