# Auto-generated by SiliconSignoffVerifier [config_hash: 6b2ed553c5c534eb]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog fsm_heldout_10_netlist.v
link_design fsm_heldout_10
read_sdc fsm_heldout_10.sdc
report_checks
report_wns
