/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_02(clk, rst_n, en, gray);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input clk;
  wire clk;
  input en;
  wire en;
  output [3:0] gray;
  wire [3:0] gray;
  wire [3:0] gray_reg;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(gray_reg[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _12_ (
    .A(gray_reg[2]),
    .B(gray_reg[3]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__xor3_1 _13_ (
    .A(gray_reg[1]),
    .B(gray_reg[2]),
    .C(gray_reg[3]),
    .X(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _14_ (
    .A(gray_reg[0]),
    .B(en),
    .Y(_07_)
  );
  sky130_fd_sc_hd__a21oi_1 _15_ (
    .A1(en),
    .A2(_06_),
    .B1(_07_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nand2_1 _16_ (
    .A(gray_reg[0]),
    .B(en),
    .Y(_08_)
  );
  sky130_fd_sc_hd__mux2_1 _17_ (
    .A0(_05_),
    .A1(gray_reg[1]),
    .S(_08_),
    .X(_01_)
  );
  sky130_fd_sc_hd__nand3b_1 _18_ (
    .A_N(gray_reg[0]),
    .B(en),
    .C(gray_reg[1]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__mux2i_1 _19_ (
    .A0(gray_reg[3]),
    .A1(_04_),
    .S(_09_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor3b_1 _20_ (
    .A(gray_reg[0]),
    .B(gray_reg[1]),
    .C_N(en),
    .Y(_10_)
  );
  sky130_fd_sc_hd__mux2_1 _21_ (
    .A0(gray_reg[3]),
    .A1(gray_reg[2]),
    .S(_10_),
    .X(_03_)
  );
  sky130_fd_sc_hd__dfrtp_1 _22_ (
    .CLK(clk),
    .D(_00_),
    .Q(gray_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _23_ (
    .CLK(clk),
    .D(_01_),
    .Q(gray_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _24_ (
    .CLK(clk),
    .D(_02_),
    .Q(gray_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _25_ (
    .CLK(clk),
    .D(_03_),
    .Q(gray_reg[3]),
    .RESET_B(rst_n)
  );
  assign gray = gray_reg;
endmodule
