# Auto-generated by SiliconSignoffVerifier [config_hash: 2cacbf36a94370af]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog counter_02_netlist.v
link_design counter_02
read_sdc counter_02.sdc
report_checks
report_wns
