# Auto-generated by SiliconSignoffVerifier [config_hash: 228f214aa5abaa9f]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog reg_if_02_netlist.v
link_design reg_if_02
read_sdc reg_if_02.sdc
report_checks
report_wns
