# Auto-generated by SiliconSignoffVerifier [config_hash: cceeac2cdf9ecfc7]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog counter_04_netlist.v
link_design counter_04
read_sdc counter_04.sdc
report_checks
report_wns
