/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module arbiter_01(clk, rst_n, req, gnt);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  input clk;
  wire clk;
  output [3:0] gnt;
  wire [3:0] gnt;
  wire [3:0] grant_reg;
  wire [1:0] priority_reg;
  input [3:0] req;
  wire [3:0] req;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__clkinv_1 _18_ (
    .A(priority_reg[0]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _19_ (
    .A(req[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__or4b_1 _20_ (
    .A(grant_reg[1]),
    .B(grant_reg[0]),
    .C(grant_reg[3]),
    .D_N(grant_reg[2]),
    .X(_05_)
  );
  sky130_fd_sc_hd__nor2_1 _21_ (
    .A(priority_reg[0]),
    .B(grant_reg[0]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o41ai_1 _22_ (
    .A1(grant_reg[2]),
    .A2(grant_reg[1]),
    .A3(grant_reg[3]),
    .A4(_06_),
    .B1(_05_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _23_ (
    .A(priority_reg[1]),
    .B(grant_reg[1]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__o41ai_1 _24_ (
    .A1(grant_reg[2]),
    .A2(grant_reg[0]),
    .A3(grant_reg[3]),
    .A4(_07_),
    .B1(_05_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _25_ (
    .A(priority_reg[0]),
    .B(priority_reg[1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__o21ai_0 _26_ (
    .A1(priority_reg[0]),
    .A2(_04_),
    .B1(priority_reg[1]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__or3_1 _27_ (
    .A(_03_),
    .B(req[1]),
    .C(req[2]),
    .X(_10_)
  );
  sky130_fd_sc_hd__a21oi_1 _28_ (
    .A1(_09_),
    .A2(_10_),
    .B1(req[3]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__o21a_1 _29_ (
    .A1(_08_),
    .A2(_11_),
    .B1(req[0]),
    .X(_00_[0])
  );
  sky130_fd_sc_hd__a21o_1 _30_ (
    .A1(_03_),
    .A2(req[0]),
    .B1(priority_reg[1]),
    .X(_12_)
  );
  sky130_fd_sc_hd__o31ai_1 _31_ (
    .A1(req[0]),
    .A2(req[3]),
    .A3(_09_),
    .B1(_12_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__and2_0 _32_ (
    .A(req[1]),
    .B(_13_),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__nand2_1 _33_ (
    .A(_03_),
    .B(priority_reg[1]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__or3_1 _34_ (
    .A(_03_),
    .B(req[0]),
    .C(req[3]),
    .X(_15_)
  );
  sky130_fd_sc_hd__a21o_1 _35_ (
    .A1(_12_),
    .A2(_15_),
    .B1(req[1]),
    .X(_16_)
  );
  sky130_fd_sc_hd__a21oi_1 _36_ (
    .A1(_14_),
    .A2(_16_),
    .B1(_04_),
    .Y(_00_[2])
  );
  sky130_fd_sc_hd__o31ai_1 _37_ (
    .A1(req[1]),
    .A2(req[2]),
    .A3(_12_),
    .B1(_09_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__and2_0 _38_ (
    .A(req[3]),
    .B(_17_),
    .X(_00_[3])
  );
  sky130_fd_sc_hd__dfrtp_1 _39_ (
    .CLK(clk),
    .D(_01_),
    .Q(priority_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _40_ (
    .CLK(clk),
    .D(_02_),
    .Q(priority_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _41_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(grant_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _42_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(grant_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _43_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(grant_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _44_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(grant_reg[3]),
    .RESET_B(rst_n)
  );
  assign gnt = grant_reg;
endmodule
