# Auto-generated by SiliconSignoffVerifier [config_hash: b5650ed4e809f854]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog arbiter_01_netlist.v
link_design arbiter_01
read_sdc arbiter_01.sdc
report_checks
report_wns
