# Auto-generated by SiliconSignoffVerifier [config_hash: 9a0e533538ece8a9]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog uart_08_netlist.v
link_design uart_08
read_sdc uart_08.sdc
report_checks
report_wns
