/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module uart_08(clk, rst_n, in_data, out_data);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  input clk;
  wire clk;
  wire [1:0] glitch_filter_counter;
  input [7:0] in_data;
  wire [7:0] in_data;
  output [7:0] out_data;
  wire [7:0] out_data;
  wire [7:0] out_data_reg;
  input rst_n;
  wire rst_n;
  wire sample_valid;
  sky130_fd_sc_hd__clkinv_1 _15_ (
    .A(glitch_filter_counter[1]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__clkinv_1 _16_ (
    .A(sample_valid),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor3b_1 _17_ (
    .A(glitch_filter_counter[0]),
    .B(glitch_filter_counter[1]),
    .C_N(sample_valid),
    .Y(_12_)
  );
  sky130_fd_sc_hd__mux2_1 _18_ (
    .A0(out_data_reg[0]),
    .A1(in_data[0]),
    .S(_12_),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _19_ (
    .A0(out_data_reg[1]),
    .A1(in_data[1]),
    .S(_12_),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _20_ (
    .A0(out_data_reg[2]),
    .A1(in_data[2]),
    .S(_12_),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _21_ (
    .A0(out_data_reg[3]),
    .A1(in_data[3]),
    .S(_12_),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _22_ (
    .A0(out_data_reg[4]),
    .A1(in_data[4]),
    .S(_12_),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _23_ (
    .A0(out_data_reg[5]),
    .A1(in_data[5]),
    .S(_12_),
    .X(_06_)
  );
  sky130_fd_sc_hd__mux2_1 _24_ (
    .A0(out_data_reg[6]),
    .A1(in_data[6]),
    .S(_12_),
    .X(_07_)
  );
  sky130_fd_sc_hd__mux2_1 _25_ (
    .A0(out_data_reg[7]),
    .A1(in_data[7]),
    .S(_12_),
    .X(_08_)
  );
  sky130_fd_sc_hd__nand2b_1 _26_ (
    .A_N(in_data[0]),
    .B(sample_valid),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o21ai_0 _27_ (
    .A1(glitch_filter_counter[0]),
    .A2(_11_),
    .B1(_13_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _28_ (
    .A(glitch_filter_counter[0]),
    .B(glitch_filter_counter[1]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2_1 _29_ (
    .A(_13_),
    .B(_14_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__dfrtp_1 _30_ (
    .CLK(clk),
    .D(_01_),
    .Q(out_data_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _31_ (
    .CLK(clk),
    .D(_02_),
    .Q(out_data_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _32_ (
    .CLK(clk),
    .D(_03_),
    .Q(out_data_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _33_ (
    .CLK(clk),
    .D(_04_),
    .Q(out_data_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _34_ (
    .CLK(clk),
    .D(_05_),
    .Q(out_data_reg[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _35_ (
    .CLK(clk),
    .D(_06_),
    .Q(out_data_reg[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _36_ (
    .CLK(clk),
    .D(_07_),
    .Q(out_data_reg[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _37_ (
    .CLK(clk),
    .D(_08_),
    .Q(out_data_reg[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _38_ (
    .CLK(clk),
    .D(_09_),
    .Q(glitch_filter_counter[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _39_ (
    .CLK(clk),
    .D(_10_),
    .Q(glitch_filter_counter[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _40_ (
    .CLK(clk),
    .D(_00_),
    .Q(sample_valid),
    .RESET_B(rst_n)
  );
  assign out_data = out_data_reg;
endmodule
