/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_04(clk, rst_n, q);
  wire [7:0] _0_;
  input clk;
  wire clk;
  output [7:0] q;
  wire [7:0] q;
  wire [7:0] q_reg;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__clkinv_1 _1_ (
    .A(q_reg[7]),
    .Y(_0_[0])
  );
  sky130_fd_sc_hd__dfrtp_1 _2_ (
    .CLK(clk),
    .D(_0_[0]),
    .Q(q_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _3_ (
    .CLK(clk),
    .D(q_reg[0]),
    .Q(q_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(clk),
    .D(q_reg[1]),
    .Q(q_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _5_ (
    .CLK(clk),
    .D(q_reg[2]),
    .Q(q_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _6_ (
    .CLK(clk),
    .D(q_reg[3]),
    .Q(q_reg[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _7_ (
    .CLK(clk),
    .D(q_reg[4]),
    .Q(q_reg[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _8_ (
    .CLK(clk),
    .D(q_reg[5]),
    .Q(q_reg[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _9_ (
    .CLK(clk),
    .D(q_reg[6]),
    .Q(q_reg[7]),
    .RESET_B(rst_n)
  );
  assign _0_[7:1] = q_reg[6:0];
  assign q = q_reg;
endmodule
