# Auto-generated by SiliconSignoffVerifier [config_hash: 8096ead1477700ad]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog spi_05_netlist.v
link_design spi_05
read_sdc spi_05.sdc
report_checks
report_wns
