/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_01(clk, rst_n, up, down, count);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  input clk;
  wire clk;
  output [7:0] count;
  wire [7:0] count;
  wire [7:0] count_reg;
  input down;
  wire down;
  input rst_n;
  wire rst_n;
  input up;
  wire up;
  sky130_fd_sc_hd__clkinv_1 _052_ (
    .A(count_reg[3]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _053_ (
    .A(count_reg[7]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _054_ (
    .A(down),
    .SLEEP(up),
    .X(_010_)
  );
  sky130_fd_sc_hd__nand2b_1 _055_ (
    .A_N(up),
    .B(down),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2_1 _056_ (
    .A(count_reg[0]),
    .B(count_reg[1]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor3_1 _057_ (
    .A(count_reg[0]),
    .B(count_reg[1]),
    .C(count_reg[2]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__or4_1 _058_ (
    .A(count_reg[0]),
    .B(count_reg[1]),
    .C(count_reg[2]),
    .D(count_reg[3]),
    .X(_014_)
  );
  sky130_fd_sc_hd__nor2_1 _059_ (
    .A(count_reg[4]),
    .B(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor3_1 _060_ (
    .A(count_reg[4]),
    .B(count_reg[5]),
    .C(_014_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor4_1 _061_ (
    .A(count_reg[4]),
    .B(count_reg[5]),
    .C(count_reg[6]),
    .D(_014_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a21oi_1 _062_ (
    .A1(_009_),
    .A2(_017_),
    .B1(_011_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a21o_1 _063_ (
    .A1(_009_),
    .A2(_017_),
    .B1(_011_),
    .X(_019_)
  );
  sky130_fd_sc_hd__nor2_1 _064_ (
    .A(count_reg[0]),
    .B(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _065_ (
    .A(up),
    .SLEEP(down),
    .X(_021_)
  );
  sky130_fd_sc_hd__nand2b_1 _066_ (
    .A_N(down),
    .B(up),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _067_ (
    .A(count_reg[0]),
    .B(count_reg[1]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__and4_1 _068_ (
    .A(count_reg[0]),
    .B(count_reg[1]),
    .C(count_reg[2]),
    .D(count_reg[3]),
    .X(_024_)
  );
  sky130_fd_sc_hd__and3_1 _069_ (
    .A(count_reg[4]),
    .B(count_reg[5]),
    .C(_024_),
    .X(_025_)
  );
  sky130_fd_sc_hd__nand4_1 _070_ (
    .A(count_reg[4]),
    .B(count_reg[5]),
    .C(count_reg[6]),
    .D(_024_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand3_1 _071_ (
    .A(count_reg[6]),
    .B(count_reg[7]),
    .C(_025_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _072_ (
    .A1(count_reg[0]),
    .A2(_027_),
    .B1(_022_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _073_ (
    .A(_010_),
    .B(_021_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a211o_1 _074_ (
    .A1(count_reg[0]),
    .A2(_029_),
    .B1(_028_),
    .C1(_020_),
    .X(_000_)
  );
  sky130_fd_sc_hd__nand2b_1 _075_ (
    .A_N(_012_),
    .B(_023_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a21oi_1 _076_ (
    .A1(_027_),
    .A2(_030_),
    .B1(_022_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a221o_1 _077_ (
    .A1(count_reg[1]),
    .A2(_029_),
    .B1(_030_),
    .B2(_018_),
    .C1(_031_),
    .X(_001_)
  );
  sky130_fd_sc_hd__o22ai_1 _078_ (
    .A1(_012_),
    .A2(_019_),
    .B1(_021_),
    .B2(_010_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__xor2_1 _079_ (
    .A(count_reg[2]),
    .B(_023_),
    .X(_033_)
  );
  sky130_fd_sc_hd__a21oi_1 _080_ (
    .A1(_027_),
    .A2(_033_),
    .B1(_022_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a221o_1 _081_ (
    .A1(_013_),
    .A2(_018_),
    .B1(_032_),
    .B2(count_reg[2]),
    .C1(_034_),
    .X(_002_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _082_ (
    .A1_N(_013_),
    .A2_N(_019_),
    .B1(_022_),
    .B2(_011_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a31oi_1 _083_ (
    .A1(count_reg[0]),
    .A2(count_reg[1]),
    .A3(count_reg[2]),
    .B1(count_reg[3]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o22ai_1 _084_ (
    .A1(_009_),
    .A2(_026_),
    .B1(_036_),
    .B2(_024_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _085_ (
    .A(_021_),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__o221ai_1 _086_ (
    .A1(_014_),
    .A2(_019_),
    .B1(_035_),
    .B2(_008_),
    .C1(_038_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__a21o_1 _087_ (
    .A1(_010_),
    .A2(_014_),
    .B1(_029_),
    .X(_039_)
  );
  sky130_fd_sc_hd__xnor2_1 _088_ (
    .A(count_reg[4]),
    .B(_024_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a21oi_1 _089_ (
    .A1(_027_),
    .A2(_040_),
    .B1(_022_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a221o_1 _090_ (
    .A1(_015_),
    .A2(_018_),
    .B1(_039_),
    .B2(count_reg[4]),
    .C1(_041_),
    .X(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _091_ (
    .A(_011_),
    .B(_015_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o21ai_0 _092_ (
    .A1(_029_),
    .A2(_042_),
    .B1(count_reg[5]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a21oi_1 _093_ (
    .A1(count_reg[4]),
    .A2(_024_),
    .B1(count_reg[5]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o22ai_1 _094_ (
    .A1(_009_),
    .A2(_026_),
    .B1(_044_),
    .B2(_025_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a22oi_1 _095_ (
    .A1(_016_),
    .A2(_018_),
    .B1(_021_),
    .B2(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _096_ (
    .A(_043_),
    .B(_046_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor2_1 _097_ (
    .A(count_reg[7]),
    .B(_026_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o21ai_0 _098_ (
    .A1(count_reg[6]),
    .A2(_025_),
    .B1(_021_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__o21bai_1 _099_ (
    .A1(_011_),
    .A2(_016_),
    .B1_N(_029_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a22oi_1 _100_ (
    .A1(_017_),
    .A2(_018_),
    .B1(_049_),
    .B2(count_reg[6]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o21ai_0 _101_ (
    .A1(_047_),
    .A2(_048_),
    .B1(_050_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__a31oi_1 _102_ (
    .A1(count_reg[6]),
    .A2(_021_),
    .A3(_025_),
    .B1(count_reg[7]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a21oi_1 _103_ (
    .A1(_010_),
    .A2(_017_),
    .B1(_051_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__dfrtp_1 _104_ (
    .CLK(clk),
    .D(_000_),
    .Q(count_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _105_ (
    .CLK(clk),
    .D(_001_),
    .Q(count_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _106_ (
    .CLK(clk),
    .D(_002_),
    .Q(count_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _107_ (
    .CLK(clk),
    .D(_003_),
    .Q(count_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _108_ (
    .CLK(clk),
    .D(_004_),
    .Q(count_reg[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _109_ (
    .CLK(clk),
    .D(_005_),
    .Q(count_reg[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _110_ (
    .CLK(clk),
    .D(_006_),
    .Q(count_reg[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _111_ (
    .CLK(clk),
    .D(_007_),
    .Q(count_reg[7]),
    .RESET_B(rst_n)
  );
  assign count = count_reg;
endmodule
