/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module arbiter_04(clk, rst_n, req, gnt);
  wire [1:0] _00_;
  wire [2:0] _01_;
  wire [2:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  input clk;
  wire clk;
  wire [1:0] count;
  output [2:0] gnt;
  wire [2:0] gnt;
  wire [2:0] gnt_reg;
  wire [2:0] grant_mask;
  input [2:0] req;
  wire [2:0] req;
  wire [2:0] req_delayed;
  input rst_n;
  wire rst_n;
  wire [2:0] weight;
  sky130_fd_sc_hd__clkinv_1 _13_ (
    .A(gnt_reg[1]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _14_ (
    .A(count[0]),
    .B(count[1]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__mux2_1 _15_ (
    .A0(grant_mask[0]),
    .A1(req_delayed[0]),
    .S(_07_),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _16_ (
    .A0(grant_mask[1]),
    .A1(req_delayed[1]),
    .S(_07_),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _17_ (
    .A0(grant_mask[2]),
    .A1(req_delayed[2]),
    .S(_07_),
    .X(_05_)
  );
  sky130_fd_sc_hd__a21oi_1 _18_ (
    .A1(gnt_reg[0]),
    .A2(_06_),
    .B1(gnt_reg[2]),
    .Y(_02_[0])
  );
  sky130_fd_sc_hd__nand2b_1 _19_ (
    .A_N(gnt_reg[2]),
    .B(gnt_reg[1]),
    .Y(_02_[1])
  );
  sky130_fd_sc_hd__nor3b_1 _20_ (
    .A(gnt_reg[1]),
    .B(gnt_reg[2]),
    .C_N(gnt_reg[0]),
    .Y(_02_[2])
  );
  sky130_fd_sc_hd__nor3_1 _21_ (
    .A(grant_mask[0]),
    .B(grant_mask[1]),
    .C(grant_mask[2]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nand2_1 _22_ (
    .A(req_delayed[2]),
    .B(weight[2]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _23_ (
    .A(req_delayed[1]),
    .B(weight[1]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor3b_1 _24_ (
    .A(_08_),
    .B(_10_),
    .C_N(_09_),
    .Y(_01_[1])
  );
  sky130_fd_sc_hd__nor2_1 _25_ (
    .A(_08_),
    .B(_09_),
    .Y(_01_[2])
  );
  sky130_fd_sc_hd__o21ba_1 _26_ (
    .A1(count[1]),
    .A2(_01_[1]),
    .B1_N(count[0]),
    .X(_00_[0])
  );
  sky130_fd_sc_hd__nand2_1 _27_ (
    .A(count[0]),
    .B(count[1]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__a21bo_1 _28_ (
    .A1(_07_),
    .A2(_01_[2]),
    .B1_N(_11_),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__nand4_1 _29_ (
    .A(req_delayed[0]),
    .B(weight[0]),
    .C(_09_),
    .D(_10_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nor2_1 _30_ (
    .A(_08_),
    .B(_12_),
    .Y(_01_[0])
  );
  sky130_fd_sc_hd__dfstp_2 _31_ (
    .CLK(clk),
    .D(_03_),
    .Q(grant_mask[0]),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _32_ (
    .CLK(clk),
    .D(_04_),
    .Q(grant_mask[1]),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _33_ (
    .CLK(clk),
    .D(_05_),
    .Q(grant_mask[2]),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _34_ (
    .CLK(clk),
    .D(_01_[0]),
    .Q(gnt_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _35_ (
    .CLK(clk),
    .D(_01_[1]),
    .Q(gnt_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _36_ (
    .CLK(clk),
    .D(_01_[2]),
    .Q(gnt_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _37_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(count[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _38_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(count[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _39_ (
    .CLK(clk),
    .D(_02_[0]),
    .Q(weight[0]),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _40_ (
    .CLK(clk),
    .D(_02_[1]),
    .Q(weight[1]),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _41_ (
    .CLK(clk),
    .D(_02_[2]),
    .Q(weight[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _42_ (
    .CLK(clk),
    .D(req[0]),
    .Q(req_delayed[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _43_ (
    .CLK(clk),
    .D(req[1]),
    .Q(req_delayed[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _44_ (
    .CLK(clk),
    .D(req[2]),
    .Q(req_delayed[2]),
    .RESET_B(rst_n)
  );
  assign gnt = gnt_reg;
endmodule
