# Auto-generated by SiliconSignoffVerifier [config_hash: 06fe10627124463c]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog arbiter_04_netlist.v
link_design arbiter_04
read_sdc arbiter_04.sdc
report_checks
report_wns
