# Auto-generated by SiliconSignoffVerifier [config_hash: b1364039e12c7f9d]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog uart_05_netlist.v
link_design uart_05
read_sdc uart_05.sdc
report_checks
report_wns
