/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_03(clk, rst_n, en, bcd_ones, bcd_tens, carry_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  output [3:0] bcd_ones;
  wire [3:0] bcd_ones;
  output [3:0] bcd_tens;
  wire [3:0] bcd_tens;
  output carry_out;
  wire carry_out;
  wire carry_out_reg;
  input clk;
  wire clk;
  input en;
  wire en;
  wire [3:0] ones_reg;
  input rst_n;
  wire rst_n;
  wire [3:0] tens_reg;
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(carry_out_reg),
    .Y(_09_)
  );
  sky130_fd_sc_hd__xor2_1 _23_ (
    .A(ones_reg[0]),
    .B(en),
    .X(_00_)
  );
  sky130_fd_sc_hd__and3_1 _24_ (
    .A(ones_reg[0]),
    .B(en),
    .C(ones_reg[3]),
    .X(_10_)
  );
  sky130_fd_sc_hd__nor2_1 _25_ (
    .A(ones_reg[1]),
    .B(ones_reg[2]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__and2_0 _26_ (
    .A(_10_),
    .B(_11_),
    .X(_12_)
  );
  sky130_fd_sc_hd__a21oi_1 _27_ (
    .A1(ones_reg[0]),
    .A2(en),
    .B1(ones_reg[1]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand3_1 _28_ (
    .A(ones_reg[0]),
    .B(en),
    .C(ones_reg[1]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor3b_1 _29_ (
    .A(_12_),
    .B(_13_),
    .C_N(_14_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__xor2_1 _30_ (
    .A(ones_reg[2]),
    .B(_14_),
    .X(_15_)
  );
  sky130_fd_sc_hd__clkinv_1 _31_ (
    .A(_15_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a41oi_1 _32_ (
    .A1(ones_reg[0]),
    .A2(en),
    .A3(ones_reg[1]),
    .A4(ones_reg[2]),
    .B1(ones_reg[3]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__a21oi_1 _33_ (
    .A1(_10_),
    .A2(_15_),
    .B1(_16_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__xor2_1 _34_ (
    .A(tens_reg[0]),
    .B(_12_),
    .X(_04_)
  );
  sky130_fd_sc_hd__nand4_1 _35_ (
    .A(tens_reg[0]),
    .B(tens_reg[3]),
    .C(_10_),
    .D(_11_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a21oi_1 _36_ (
    .A1(tens_reg[0]),
    .A2(_12_),
    .B1(tens_reg[1]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nand4_1 _37_ (
    .A(tens_reg[0]),
    .B(tens_reg[1]),
    .C(_10_),
    .D(_11_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__o31ai_1 _38_ (
    .A1(tens_reg[1]),
    .A2(tens_reg[2]),
    .A3(_17_),
    .B1(_19_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nor2_1 _39_ (
    .A(_18_),
    .B(_20_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _40_ (
    .A(tens_reg[2]),
    .SLEEP(_19_),
    .X(_21_)
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(tens_reg[2]),
    .B(_19_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o22a_1 _42_ (
    .A1(tens_reg[3]),
    .A2(_21_),
    .B1(_06_),
    .B2(_17_),
    .X(_07_)
  );
  sky130_fd_sc_hd__o32ai_1 _43_ (
    .A1(tens_reg[1]),
    .A2(tens_reg[2]),
    .A3(_17_),
    .B1(_09_),
    .B2(en),
    .Y(_08_)
  );
  sky130_fd_sc_hd__dfrtp_1 _44_ (
    .CLK(clk),
    .D(_00_),
    .Q(ones_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _45_ (
    .CLK(clk),
    .D(_01_),
    .Q(ones_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _46_ (
    .CLK(clk),
    .D(_02_),
    .Q(ones_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _47_ (
    .CLK(clk),
    .D(_03_),
    .Q(ones_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _48_ (
    .CLK(clk),
    .D(_04_),
    .Q(tens_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _49_ (
    .CLK(clk),
    .D(_05_),
    .Q(tens_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _50_ (
    .CLK(clk),
    .D(_06_),
    .Q(tens_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _51_ (
    .CLK(clk),
    .D(_07_),
    .Q(tens_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _52_ (
    .CLK(clk),
    .D(_08_),
    .Q(carry_out_reg),
    .RESET_B(rst_n)
  );
  assign bcd_ones = ones_reg;
  assign bcd_tens = tens_reg;
  assign carry_out = carry_out_reg;
endmodule
