# Auto-generated by SiliconSignoffVerifier [config_hash: a452b2320dc60ea0]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog counter_03_netlist.v
link_design counter_03
read_sdc counter_03.sdc
report_checks
report_wns
