"""Evidence-based tapeout-readiness checks.

This module intentionally does *not* call a four-step OSS flow "signoff".
It validates that required, externally-produced signoff evidence exists and is
clean before a run may be described as tapeout-ready.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class AssuranceCheck(BaseModel):
    """One independently-produced design-assurance receipt."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    name: str = Field(min_length=1)
    report: str = Field(min_length=1, description="Path relative to workspace")
    required: bool = True
    pass_patterns: list[str] = Field(default_factory=lambda: ["PASS", "CLEAN", "MET"])
    fail_patterns: list[str] = Field(
        default_factory=lambda: ["FAIL", "ERROR", "VIOLATED", "UNRESOLVED"]
    )


class TapeoutReadinessPolicy(BaseModel):
    """Explicit evidence required before a design is called tapeout-ready.

    The defaults cover the major digital signoff disciplines.  Users must
    point each check at a report generated by their qualified tool/PDK flow.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    checks: list[AssuranceCheck] = Field(default_factory=lambda: [
        AssuranceCheck(name="lint", report="signoff/lint.rpt"),
        AssuranceCheck(name="cdc_rdc", report="signoff/cdc_rdc.rpt"),
        AssuranceCheck(name="formal_equivalence", report="signoff/lec.rpt"),
        AssuranceCheck(name="low_power", report="signoff/upf.rpt"),
        AssuranceCheck(name="dft", report="signoff/dft.rpt"),
        AssuranceCheck(name="sta_mcmm", report="signoff/sta_mcmm.rpt"),
        AssuranceCheck(name="physical_drc_lvs", report="signoff/drc_lvs.rpt"),
        AssuranceCheck(name="reliability_emir", report="signoff/emir.rpt"),
    ])


class TapeoutReadinessVerifier:
    """Fail closed unless every required external assurance receipt is clean."""

    def __init__(self, policy: TapeoutReadinessPolicy | None = None) -> None:
        self.policy = policy or TapeoutReadinessPolicy()

    def verify(self, workspace: Path | str) -> dict[str, Any]:
        root = Path(workspace).resolve()
        receipts: list[dict[str, Any]] = []
        for check in self.policy.checks:
            report = (root / check.report).resolve()
            if not report.is_relative_to(root):
                receipts.append({"name": check.name, "passed": False, "reason": "path traversal"})
                continue
            if not report.is_file():
                receipts.append({"name": check.name, "passed": not check.required, "reason": "report missing"})
                continue
            text = report.read_text(encoding="utf-8", errors="replace").upper()
            failures = [p for p in check.fail_patterns if p.upper() in text]
            successes = [p for p in check.pass_patterns if p.upper() in text]
            passed = not failures and bool(successes)
            receipts.append({
                "name": check.name,
                "report": check.report,
                "passed": passed,
                "reason": "clean receipt" if passed else "missing PASS/CLEAN/MET marker or failure marker found",
            })
        return {
            "tapeout_ready": all(r["passed"] for r in receipts),
            "receipts": receipts,
        }

    def write_template(self, workspace: Path | str) -> Path:
        """Write a reviewable policy template; never fabricate signoff reports."""
        path = Path(workspace).resolve() / "tapeout-readiness-policy.json"
        path.write_text(self.policy.model_dump_json(indent=2) + "\n", encoding="utf-8")
        return path

