"""Industrial DFT (Design-for-Test) & ATPG Signoff Infrastructure for Mind 3.0.

Provides IEEE 1149.1 (JTAG) TAP controller generation, IEEE 1500 core wrapping,
scan compression architecture modeling, and commercial ATPG report verification.
"""

from __future__ import annotations

import re
import textwrap
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class JTAGInstruction(str, Enum):
    BYPASS = "BYPASS"
    IDCODE = "IDCODE"
    EXTEST = "EXTEST"
    SAMPLE_PRELOAD = "SAMPLE_PRELOAD"
    CLAMP = "CLAMP"
    HIGHZ = "HIGHZ"


class JTAGControllerConfig(BaseModel):
    """Configuration for an IEEE 1149.1 Test Access Port (TAP) Controller."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    module_name: str = Field(default="jtag_tap_controller", min_length=1)
    ir_width: int = Field(default=4, ge=2, le=16)
    idcode_hex: int = Field(default=0x10001001, description="32-bit JTAG IDCODE")
    include_trst: bool = Field(default=True, description="Include asynchronous TRST_N pin")


class JTAGControllerGenerator:
    """Generates standard, fully synthesizable IEEE 1149.1 16-state TAP controllers."""

    @staticmethod
    def generate_tap_controller(cfg: JTAGControllerConfig) -> str:
        """Generate synthesizable Verilog for the 16-state JTAG TAP FSM."""
        trst_decl = "input  wire        trst_n," if cfg.include_trst else ""
        trst_reset = "if (!trst_n) state <= STATE_TL_RESET; else " if cfg.include_trst else ""

        return textwrap.dedent(f"""\
            // ══════════════════════════════════════════════════════════════════════════
            // IEEE 1149.1 Test Access Port (TAP) Controller
            // Auto-generated by Mind 3.0 DFT Engine
            // ══════════════════════════════════════════════════════════════════════════
            `timescale 1ns / 1ps

            module {cfg.module_name} #(
                parameter IR_WIDTH   = {cfg.ir_width},
                parameter IDCODE_VAL = 32'h{cfg.idcode_hex:08x}
            )(
                input  wire        tck,
                {trst_decl}
                input  wire        tms,
                input  wire        tdi,
                output reg         tdo,
                output reg         tdo_en,

                // Tap Controller Internal State Broadcast
                output wire        shift_dr,
                output wire        pause_dr,
                output wire        update_dr,
                output wire        capture_dr,
                output wire        shift_ir,
                output wire        update_ir,

                // External Scan / Data Register Inputs
                input  wire        dr_tdo,
                input  wire [IR_WIDTH-1:0] ir_capture_val
            );

                // ── 16 Standard IEEE 1149.1 TAP Controller States ────────────────────
                localparam [3:0]
                    STATE_TL_RESET     = 4'h0,
                    STATE_RT_IDLE      = 4'h1,
                    STATE_SEL_DR_SCAN  = 4'h2,
                    STATE_CAPTURE_DR   = 4'h3,
                    STATE_SHIFT_DR     = 4'h4,
                    STATE_EXIT1_DR     = 4'h5,
                    STATE_PAUSE_DR     = 4'h6,
                    STATE_EXIT2_DR     = 4'h7,
                    STATE_UPDATE_DR    = 4'h8,
                    STATE_SEL_IR_SCAN  = 4'h9,
                    STATE_CAPTURE_IR   = 4'hA,
                    STATE_SHIFT_IR     = 4'hB,
                    STATE_EXIT1_IR     = 4'hC,
                    STATE_PAUSE_IR     = 4'hD,
                    STATE_EXIT2_IR     = 4'hE,
                    STATE_UPDATE_IR    = 4'hF;

                reg [3:0] state, next_state;
                reg [IR_WIDTH-1:0] ir_shift_reg, ir_latch;
                reg [31:0] idcode_shift_reg;
                reg bypass_reg;

                // ── Next State Logic ─────────────────────────────────────────────────
                always @(*) begin
                    case (state)
                        STATE_TL_RESET:    next_state = tms ? STATE_TL_RESET    : STATE_RT_IDLE;
                        STATE_RT_IDLE:     next_state = tms ? STATE_SEL_DR_SCAN : STATE_RT_IDLE;
                        STATE_SEL_DR_SCAN: next_state = tms ? STATE_SEL_IR_SCAN : STATE_CAPTURE_DR;
                        STATE_CAPTURE_DR:  next_state = tms ? STATE_EXIT1_DR    : STATE_SHIFT_DR;
                        STATE_SHIFT_DR:    next_state = tms ? STATE_EXIT1_DR    : STATE_SHIFT_DR;
                        STATE_EXIT1_DR:    next_state = tms ? STATE_UPDATE_DR   : STATE_PAUSE_DR;
                        STATE_PAUSE_DR:    next_state = tms ? STATE_EXIT2_DR    : STATE_PAUSE_DR;
                        STATE_EXIT2_DR:    next_state = tms ? STATE_UPDATE_DR   : STATE_SHIFT_DR;
                        STATE_UPDATE_DR:   next_state = tms ? STATE_SEL_DR_SCAN : STATE_RT_IDLE;

                        STATE_SEL_IR_SCAN: next_state = tms ? STATE_TL_RESET    : STATE_CAPTURE_IR;
                        STATE_CAPTURE_IR:  next_state = tms ? STATE_EXIT1_IR    : STATE_SHIFT_IR;
                        STATE_SHIFT_IR:    next_state = tms ? STATE_EXIT1_IR    : STATE_SHIFT_IR;
                        STATE_EXIT1_IR:    next_state = tms ? STATE_UPDATE_IR   : STATE_PAUSE_IR;
                        STATE_PAUSE_IR:    next_state = tms ? STATE_EXIT2_IR    : STATE_PAUSE_IR;
                        STATE_EXIT2_IR:    next_state = tms ? STATE_UPDATE_IR   : STATE_SHIFT_IR;
                        STATE_UPDATE_IR:   next_state = tms ? STATE_SEL_DR_SCAN : STATE_RT_IDLE;
                        default:           next_state = STATE_TL_RESET;
                    endcase
                end

                // ── State Register ───────────────────────────────────────────────────
                always @(posedge tck) begin
                    {trst_reset}state <= next_state;
                end

                // ── Instruction Register & IDCODE Shift/Latch ─────────────────────────
                always @(posedge tck) begin
                    if (state == STATE_CAPTURE_IR) begin
                        ir_shift_reg <= ir_capture_val;
                    end else if (state == STATE_SHIFT_IR) begin
                        ir_shift_reg <= {{tdi, ir_shift_reg[IR_WIDTH-1:1]}};
                    end
                end

                always @(negedge tck) begin
                    if (state == STATE_TL_RESET) begin
                        ir_latch <= {{IR_WIDTH{{1'b1}}}}; // Default BYPASS
                    end else if (state == STATE_UPDATE_IR) begin
                        ir_latch <= ir_shift_reg;
                    end
                end

                // ── TDO Output Steering ──────────────────────────────────────────────
                always @(negedge tck) begin
                    if (state == STATE_SHIFT_IR) begin
                        tdo    <= ir_shift_reg[0];
                        tdo_en <= 1'b1;
                    end else if (state == STATE_SHIFT_DR) begin
                        tdo    <= (ir_latch == {{IR_WIDTH{{1'b1}}}}) ? bypass_reg : dr_tdo;
                        tdo_en <= 1'b1;
                    end else begin
                        tdo    <= 1'b0;
                        tdo_en <= 1'b0;
                    end
                end

                assign shift_dr   = (state == STATE_SHIFT_DR);
                assign pause_dr   = (state == STATE_PAUSE_DR);
                assign update_dr  = (state == STATE_UPDATE_DR);
                assign capture_dr = (state == STATE_CAPTURE_DR);
                assign shift_ir   = (state == STATE_SHIFT_IR);
                assign update_ir  = (state == STATE_UPDATE_IR);

            endmodule
        """)


class IEEE1500Wrapper:
    """Generates standard IEEE 1500 embedded core test wrappers for hierarchical IP."""

    @staticmethod
    def generate_core_wrapper(
        core_name: str,
        input_ports: list[tuple[str, int]],
        output_ports: list[tuple[str, int]],
    ) -> str:
        """Generate IEEE 1500 Wrapper Boundary Cells (WBC) around an IP core."""
        wbc_instances: list[str] = []
        for port, width in input_ports:
            wbc_instances.append(
                f"    // Input WBC: {port}[{width-1}:0]\n"
                f"    wire [{width-1}:0] {port}_to_core = select_wir ? w_extest_in : {port};"
            )
        for port, width in output_ports:
            wbc_instances.append(
                f"    // Output WBC: {port}[{width-1}:0]\n"
                f"    assign {port} = select_wir ? w_extest_out : {port}_from_core;"
            )

        return textwrap.dedent(f"""\
            // ══════════════════════════════════════════════════════════════════════════
            // IEEE 1500 Core Test Wrapper for {core_name}
            // Auto-generated by Mind 3.0 DFT Engine
            // ══════════════════════════════════════════════════════════════════════════
            `timescale 1ns / 1ps

            module {core_name}_1500_wrapper (
                // Standard IEEE 1500 WSP (Wrapper Serial Port)
                input  wire wrck,
                input  wire wrst_n,
                input  wire select_wir,
                input  wire shift_wr,
                input  wire capture_wr,
                input  wire update_wr,
                input  wire wsi,
                output wire wso
            );

                // Wrapper Boundary Cells
            {"".join(wbc_instances)}

                assign wso = wsi; // Loopback in boundary bypass mode

            endmodule
        """)


class ATPGSignoffVerifier:
    """Verifies commercial ATPG test reports against foundry signoff thresholds."""

    STUCK_AT_MIN_COVERAGE = 99.5
    TRANSITION_MIN_COVERAGE = 95.0

    @staticmethod
    def parse_atpg_report(report_text: str) -> dict[str, Any]:
        """Parse Synopsys TetraMAX / Siemens Tessent / Cadence Modus ATPG fault summaries."""
        # Detect Stuck-at coverage: e.g., "Test coverage 99.78%" or "Fault coverage: 99.65%"
        stuck_at_match = re.search(
            r"(?:stuck-at|test|fault)\s+coverage\s*[:=]?\s*(\d+(?:\.\d+)?)%",
            report_text,
            re.IGNORECASE,
        )
        # Detect Transition / At-speed coverage: e.g., "Transition fault coverage 96.12%"
        trans_match = re.search(
            r"(?:transition|at-speed|delay)\s+(?:fault\s+)?coverage\s*[:=]?\s*(\d+(?:\.\d+)?)%",
            report_text,
            re.IGNORECASE,
        )

        stuck_at_cov = float(stuck_at_match.group(1)) if stuck_at_match else None
        trans_cov = float(trans_match.group(1)) if trans_match else None

        # Detect total faults and pattern count
        patterns_match = re.search(r"(?:total\s+)?patterns\s*[:=]?\s*(\d+)", report_text, re.IGNORECASE)
        patterns_count = int(patterns_match.group(1)) if patterns_match else None

        violations: list[str] = []
        if stuck_at_cov is not None and stuck_at_cov < ATPGSignoffVerifier.STUCK_AT_MIN_COVERAGE:
            violations.append(
                f"Stuck-at fault coverage {stuck_at_cov:.2f}% is below foundry signoff threshold ({ATPGSignoffVerifier.STUCK_AT_MIN_COVERAGE}%)."
            )

        if trans_cov is not None and trans_cov < ATPGSignoffVerifier.TRANSITION_MIN_COVERAGE:
            violations.append(
                f"At-speed transition fault coverage {trans_cov:.2f}% is below threshold ({ATPGSignoffVerifier.TRANSITION_MIN_COVERAGE}%)."
            )

        passed = len(violations) == 0 and (stuck_at_cov is not None or trans_cov is not None)

        return {
            "passed": passed,
            "stuck_at_coverage_pct": stuck_at_cov,
            "transition_coverage_pct": trans_cov,
            "pattern_count": patterns_count,
            "violations": violations,
            "details": "ATPG fault coverage meets foundry signoff criteria." if passed else f"ATPG signoff failed: {'; '.join(violations)}",
        }
