/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_10(clk, rst_n, strobe, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  input clk;
  wire clk;
  output [7:0] count;
  wire [7:0] count;
  wire [7:0] count_reg;
  input rst_n;
  wire rst_n;
  input strobe;
  wire strobe;
  wire strobe_prev;
  sky130_fd_sc_hd__xor2_1 _16_ (
    .A(strobe),
    .B(strobe_prev),
    .X(_08_)
  );
  sky130_fd_sc_hd__nand2_1 _17_ (
    .A(count_reg[0]),
    .B(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__xor2_1 _18_ (
    .A(count_reg[0]),
    .B(_08_),
    .X(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _19_ (
    .A(count_reg[1]),
    .B(_09_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__a31oi_1 _20_ (
    .A1(count_reg[0]),
    .A2(count_reg[1]),
    .A3(_08_),
    .B1(count_reg[2]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nand4_1 _21_ (
    .A(count_reg[0]),
    .B(count_reg[1]),
    .C(count_reg[2]),
    .D(_08_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor2b_1 _22_ (
    .A(_10_),
    .B_N(_11_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _23_ (
    .A(count_reg[3]),
    .SLEEP(_11_),
    .X(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _24_ (
    .A(count_reg[3]),
    .B(_11_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nand2_1 _25_ (
    .A(count_reg[4]),
    .B(_12_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__xor2_1 _26_ (
    .A(count_reg[4]),
    .B(_12_),
    .X(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _27_ (
    .A(count_reg[5]),
    .B(_13_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand4_1 _28_ (
    .A(count_reg[4]),
    .B(count_reg[5]),
    .C(count_reg[6]),
    .D(_12_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__a31oi_1 _29_ (
    .A1(count_reg[4]),
    .A2(count_reg[5]),
    .A3(_12_),
    .B1(count_reg[6]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _30_ (
    .A(_14_),
    .SLEEP(_15_),
    .X(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _31_ (
    .A(count_reg[7]),
    .B(_14_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__dfrtp_1 _32_ (
    .CLK(clk),
    .D(strobe),
    .Q(strobe_prev),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _33_ (
    .CLK(clk),
    .D(_00_),
    .Q(count_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _34_ (
    .CLK(clk),
    .D(_01_),
    .Q(count_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _35_ (
    .CLK(clk),
    .D(_02_),
    .Q(count_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _36_ (
    .CLK(clk),
    .D(_03_),
    .Q(count_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _37_ (
    .CLK(clk),
    .D(_04_),
    .Q(count_reg[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _38_ (
    .CLK(clk),
    .D(_05_),
    .Q(count_reg[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _39_ (
    .CLK(clk),
    .D(_06_),
    .Q(count_reg[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _40_ (
    .CLK(clk),
    .D(_07_),
    .Q(count_reg[7]),
    .RESET_B(rst_n)
  );
  assign count = count_reg;
endmodule
