# Auto-generated by SiliconSignoffVerifier [config_hash: 1e0326fa48006698]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog counter_10_netlist.v
link_design counter_10
read_sdc counter_10.sdc
report_checks
report_wns
