/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_09(clk, rst_n, lfsr_out);
  wire [7:0] _00_;
  wire _01_;
  input clk;
  wire clk;
  output [7:0] lfsr_out;
  wire [7:0] lfsr_out;
  wire [7:0] lfsr_reg;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__xnor3_1 _02_ (
    .A(lfsr_reg[7]),
    .B(lfsr_reg[5]),
    .C(lfsr_reg[4]),
    .X(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _03_ (
    .A(lfsr_reg[3]),
    .B(_01_),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__dfstp_2 _04_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(lfsr_reg[0]),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _05_ (
    .CLK(clk),
    .D(lfsr_reg[0]),
    .Q(lfsr_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _06_ (
    .CLK(clk),
    .D(lfsr_reg[1]),
    .Q(lfsr_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _07_ (
    .CLK(clk),
    .D(lfsr_reg[2]),
    .Q(lfsr_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _08_ (
    .CLK(clk),
    .D(lfsr_reg[3]),
    .Q(lfsr_reg[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _09_ (
    .CLK(clk),
    .D(lfsr_reg[4]),
    .Q(lfsr_reg[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _10_ (
    .CLK(clk),
    .D(lfsr_reg[5]),
    .Q(lfsr_reg[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _11_ (
    .CLK(clk),
    .D(lfsr_reg[6]),
    .Q(lfsr_reg[7]),
    .RESET_B(rst_n)
  );
  assign _00_[7:1] = lfsr_reg[6:0];
  assign lfsr_out = lfsr_reg;
endmodule
