# Auto-generated by SiliconSignoffVerifier [config_hash: 44fa9f394c23d1cf]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog counter_09_netlist.v
link_design counter_09
read_sdc counter_09.sdc
report_checks
report_wns
