/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module arbiter_08(clk, rst_n, cluster_req, gnt);
  wire [3:0] _0_;
  input clk;
  wire clk;
  input [3:0] cluster_req;
  wire [3:0] cluster_req;
  output [3:0] gnt;
  wire [3:0] gnt;
  wire [3:0] gnt_reg;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1_ (
    .A(cluster_req[2]),
    .SLEEP(cluster_req[3]),
    .X(_0_[1])
  );
  sky130_fd_sc_hd__nor3b_1 _2_ (
    .A(cluster_req[2]),
    .B(cluster_req[3]),
    .C_N(cluster_req[1]),
    .Y(_0_[2])
  );
  sky130_fd_sc_hd__nor4b_1 _3_ (
    .A(cluster_req[1]),
    .B(cluster_req[2]),
    .C(cluster_req[3]),
    .D_N(cluster_req[0]),
    .Y(_0_[3])
  );
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(clk),
    .D(cluster_req[3]),
    .Q(gnt_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _5_ (
    .CLK(clk),
    .D(_0_[1]),
    .Q(gnt_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _6_ (
    .CLK(clk),
    .D(_0_[2]),
    .Q(gnt_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _7_ (
    .CLK(clk),
    .D(_0_[3]),
    .Q(gnt_reg[3]),
    .RESET_B(rst_n)
  );
  assign _0_[0] = cluster_req[3];
  assign gnt = gnt_reg;
endmodule
