# Auto-generated by SiliconSignoffVerifier [config_hash: 5d1a23f0b13ddfb7]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog arbiter_08_netlist.v
link_design arbiter_08
read_sdc arbiter_08.sdc
report_checks
report_wns
