/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module reg_if_06(clk, rst_n, in_data, out_data);
  wire [7:0] _00_;
  input clk;
  wire clk;
  input [7:0] in_data;
  wire [7:0] in_data;
  wire [7:0] interrupt_status;
  output [7:0] out_data;
  wire [7:0] out_data;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _01_ (
    .A(interrupt_status[1]),
    .SLEEP(in_data[1]),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _02_ (
    .A(interrupt_status[2]),
    .SLEEP(in_data[2]),
    .X(_00_[2])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _03_ (
    .A(interrupt_status[3]),
    .SLEEP(in_data[3]),
    .X(_00_[3])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _04_ (
    .A(interrupt_status[4]),
    .SLEEP(in_data[4]),
    .X(_00_[4])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _05_ (
    .A(interrupt_status[5]),
    .SLEEP(in_data[5]),
    .X(_00_[5])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _06_ (
    .A(interrupt_status[6]),
    .SLEEP(in_data[6]),
    .X(_00_[6])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _07_ (
    .A(interrupt_status[7]),
    .SLEEP(in_data[7]),
    .X(_00_[7])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _08_ (
    .A(interrupt_status[0]),
    .SLEEP(in_data[0]),
    .X(_00_[0])
  );
  sky130_fd_sc_hd__dfrtp_1 _09_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(interrupt_status[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _10_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(interrupt_status[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _11_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(interrupt_status[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _12_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(interrupt_status[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _13_ (
    .CLK(clk),
    .D(_00_[4]),
    .Q(interrupt_status[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _14_ (
    .CLK(clk),
    .D(_00_[5]),
    .Q(interrupt_status[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _15_ (
    .CLK(clk),
    .D(_00_[6]),
    .Q(interrupt_status[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _16_ (
    .CLK(clk),
    .D(_00_[7]),
    .Q(interrupt_status[7]),
    .RESET_B(rst_n)
  );
  assign out_data = interrupt_status;
endmodule
