# Auto-generated by SiliconSignoffVerifier [config_hash: a1ba72631828a877]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog arbiter_05_netlist.v
link_design arbiter_05
read_sdc arbiter_05.sdc
report_checks
report_wns
