/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_01(clk, rst_n, up, down, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  input clk;
  wire clk;
  output [7:0] count;
  wire [7:0] count;
  wire [7:0] count_reg;
  input down;
  wire down;
  input rst_n;
  wire rst_n;
  input up;
  wire up;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _43_ (
    .A(up),
    .SLEEP(down),
    .X(_08_)
  );
  sky130_fd_sc_hd__nand2b_1 _44_ (
    .A_N(down),
    .B(up),
    .Y(_09_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _45_ (
    .A(down),
    .SLEEP(up),
    .X(_10_)
  );
  sky130_fd_sc_hd__or3_1 _46_ (
    .A(count_reg[0]),
    .B(count_reg[1]),
    .C(count_reg[2]),
    .X(_11_)
  );
  sky130_fd_sc_hd__or4_1 _47_ (
    .A(count_reg[0]),
    .B(count_reg[1]),
    .C(count_reg[2]),
    .D(count_reg[3]),
    .X(_12_)
  );
  sky130_fd_sc_hd__nor2_1 _48_ (
    .A(count_reg[4]),
    .B(_12_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__or4_1 _49_ (
    .A(count_reg[4]),
    .B(count_reg[5]),
    .C(count_reg[6]),
    .D(_12_),
    .X(_14_)
  );
  sky130_fd_sc_hd__o21ai_0 _50_ (
    .A1(count_reg[7]),
    .A2(_14_),
    .B1(_10_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__a21oi_1 _51_ (
    .A1(_09_),
    .A2(_15_),
    .B1(count_reg[0]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nand2_1 _52_ (
    .A(count_reg[0]),
    .B(count_reg[1]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__and4_1 _53_ (
    .A(count_reg[0]),
    .B(count_reg[1]),
    .C(count_reg[2]),
    .D(count_reg[3]),
    .X(_18_)
  );
  sky130_fd_sc_hd__and3_1 _54_ (
    .A(count_reg[4]),
    .B(count_reg[5]),
    .C(_18_),
    .X(_19_)
  );
  sky130_fd_sc_hd__nand3_1 _55_ (
    .A(count_reg[6]),
    .B(count_reg[7]),
    .C(_19_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a21boi_0 _56_ (
    .A1(_08_),
    .A2(_20_),
    .B1_N(_15_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__a21o_1 _57_ (
    .A1(count_reg[0]),
    .A2(_21_),
    .B1(_16_),
    .X(_00_)
  );
  sky130_fd_sc_hd__xor2_1 _58_ (
    .A(count_reg[0]),
    .B(count_reg[1]),
    .X(_22_)
  );
  sky130_fd_sc_hd__nor2_1 _59_ (
    .A(_15_),
    .B(_22_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__a221o_1 _60_ (
    .A1(count_reg[1]),
    .A2(_21_),
    .B1(_22_),
    .B2(_08_),
    .C1(_23_),
    .X(_01_)
  );
  sky130_fd_sc_hd__o21ai_0 _61_ (
    .A1(count_reg[0]),
    .A2(count_reg[1]),
    .B1(count_reg[2]),
    .Y(_24_)
  );
  sky130_fd_sc_hd__a21oi_1 _62_ (
    .A1(_11_),
    .A2(_24_),
    .B1(_15_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__xnor2_1 _63_ (
    .A(count_reg[2]),
    .B(_17_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__a221o_1 _64_ (
    .A1(count_reg[2]),
    .A2(_21_),
    .B1(_26_),
    .B2(_08_),
    .C1(_25_),
    .X(_02_)
  );
  sky130_fd_sc_hd__nand2_1 _65_ (
    .A(count_reg[3]),
    .B(_11_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__a21oi_1 _66_ (
    .A1(_12_),
    .A2(_27_),
    .B1(_15_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__a31oi_1 _67_ (
    .A1(count_reg[0]),
    .A2(count_reg[1]),
    .A3(count_reg[2]),
    .B1(count_reg[3]),
    .Y(_29_)
  );
  sky130_fd_sc_hd__nor3_1 _68_ (
    .A(_09_),
    .B(_18_),
    .C(_29_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__a211o_1 _69_ (
    .A1(count_reg[3]),
    .A2(_21_),
    .B1(_28_),
    .C1(_30_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xor2_1 _70_ (
    .A(count_reg[4]),
    .B(_12_),
    .X(_31_)
  );
  sky130_fd_sc_hd__nor2_1 _71_ (
    .A(_15_),
    .B(_31_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__xor2_1 _72_ (
    .A(count_reg[4]),
    .B(_18_),
    .X(_33_)
  );
  sky130_fd_sc_hd__a221o_1 _73_ (
    .A1(count_reg[4]),
    .A2(_21_),
    .B1(_33_),
    .B2(_08_),
    .C1(_32_),
    .X(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _74_ (
    .A(count_reg[5]),
    .B(_13_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nor2_1 _75_ (
    .A(_15_),
    .B(_34_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__a21oi_1 _76_ (
    .A1(count_reg[4]),
    .A2(_18_),
    .B1(count_reg[5]),
    .Y(_36_)
  );
  sky130_fd_sc_hd__nor2_1 _77_ (
    .A(_19_),
    .B(_36_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__a221o_1 _78_ (
    .A1(count_reg[5]),
    .A2(_21_),
    .B1(_37_),
    .B2(_08_),
    .C1(_35_),
    .X(_05_)
  );
  sky130_fd_sc_hd__o31ai_1 _79_ (
    .A1(count_reg[4]),
    .A2(count_reg[5]),
    .A3(_12_),
    .B1(count_reg[6]),
    .Y(_38_)
  );
  sky130_fd_sc_hd__a21oi_1 _80_ (
    .A1(_14_),
    .A2(_38_),
    .B1(_15_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__xor2_1 _81_ (
    .A(count_reg[6]),
    .B(_19_),
    .X(_40_)
  );
  sky130_fd_sc_hd__a221o_1 _82_ (
    .A1(count_reg[6]),
    .A2(_21_),
    .B1(_40_),
    .B2(_08_),
    .C1(_39_),
    .X(_06_)
  );
  sky130_fd_sc_hd__a31oi_1 _83_ (
    .A1(count_reg[6]),
    .A2(_08_),
    .A3(_19_),
    .B1(count_reg[7]),
    .Y(_41_)
  );
  sky130_fd_sc_hd__nor4bb_1 _84_ (
    .A(up),
    .B(_14_),
    .C_N(count_reg[7]),
    .D_N(down),
    .Y(_42_)
  );
  sky130_fd_sc_hd__nor2_1 _85_ (
    .A(_41_),
    .B(_42_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__dfrtp_1 _86_ (
    .CLK(clk),
    .D(_00_),
    .Q(count_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _87_ (
    .CLK(clk),
    .D(_01_),
    .Q(count_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _88_ (
    .CLK(clk),
    .D(_02_),
    .Q(count_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _89_ (
    .CLK(clk),
    .D(_03_),
    .Q(count_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _90_ (
    .CLK(clk),
    .D(_04_),
    .Q(count_reg[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _91_ (
    .CLK(clk),
    .D(_05_),
    .Q(count_reg[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _92_ (
    .CLK(clk),
    .D(_06_),
    .Q(count_reg[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _93_ (
    .CLK(clk),
    .D(_07_),
    .Q(count_reg[7]),
    .RESET_B(rst_n)
  );
  assign count = count_reg;
endmodule
