# Auto-generated by SiliconSignoffVerifier [config_hash: a2f65789124ec0a5]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog counter_01_netlist.v
link_design counter_01
read_sdc counter_01.sdc
report_checks
report_wns
