# Auto-generated by SiliconSignoffVerifier [config_hash: c362f361d7a189a1]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog spi_08_netlist.v
link_design spi_08
read_sdc spi_08.sdc
report_checks
report_wns
