/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module fifo_02(clk, rst_n, s_valid, s_ready, s_data, m_valid, m_ready, m_data);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  input clk;
  wire clk;
  output [7:0] m_data;
  wire [7:0] m_data;
  input m_ready;
  wire m_ready;
  output m_valid;
  wire m_valid;
  input rst_n;
  wire rst_n;
  input [7:0] s_data;
  wire [7:0] s_data;
  output s_ready;
  wire s_ready;
  input s_valid;
  wire s_valid;
  wire [7:0] stage1_data;
  wire stage1_valid;
  wire [7:0] stage2_data;
  wire stage2_valid;
  sky130_fd_sc_hd__mux2_1 _16_ (
    .A0(stage1_data[6]),
    .A1(s_data[6]),
    .S(s_valid),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux2_1 _17_ (
    .A0(stage1_data[7]),
    .A1(s_data[7]),
    .S(s_valid),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _18_ (
    .A0(stage2_data[0]),
    .A1(stage1_data[0]),
    .S(s_valid),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _19_ (
    .A0(stage2_data[1]),
    .A1(stage1_data[1]),
    .S(s_valid),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _20_ (
    .A0(stage2_data[2]),
    .A1(stage1_data[2]),
    .S(s_valid),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _21_ (
    .A0(stage2_data[3]),
    .A1(stage1_data[3]),
    .S(s_valid),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _22_ (
    .A0(stage2_data[4]),
    .A1(stage1_data[4]),
    .S(s_valid),
    .X(_06_)
  );
  sky130_fd_sc_hd__mux2_1 _23_ (
    .A0(stage2_data[5]),
    .A1(stage1_data[5]),
    .S(s_valid),
    .X(_07_)
  );
  sky130_fd_sc_hd__mux2_1 _24_ (
    .A0(stage2_data[6]),
    .A1(stage1_data[6]),
    .S(s_valid),
    .X(_08_)
  );
  sky130_fd_sc_hd__mux2_1 _25_ (
    .A0(stage2_data[7]),
    .A1(stage1_data[7]),
    .S(s_valid),
    .X(_09_)
  );
  sky130_fd_sc_hd__mux2_1 _26_ (
    .A0(stage1_data[0]),
    .A1(s_data[0]),
    .S(s_valid),
    .X(_10_)
  );
  sky130_fd_sc_hd__mux2_1 _27_ (
    .A0(stage1_data[1]),
    .A1(s_data[1]),
    .S(s_valid),
    .X(_11_)
  );
  sky130_fd_sc_hd__mux2_1 _28_ (
    .A0(stage1_data[2]),
    .A1(s_data[2]),
    .S(s_valid),
    .X(_12_)
  );
  sky130_fd_sc_hd__mux2_1 _29_ (
    .A0(stage1_data[3]),
    .A1(s_data[3]),
    .S(s_valid),
    .X(_13_)
  );
  sky130_fd_sc_hd__mux2_1 _30_ (
    .A0(stage1_data[4]),
    .A1(s_data[4]),
    .S(s_valid),
    .X(_14_)
  );
  sky130_fd_sc_hd__mux2_1 _31_ (
    .A0(stage1_data[5]),
    .A1(s_data[5]),
    .S(s_valid),
    .X(_15_)
  );
  sky130_fd_sc_hd__nand2b_1 _32_ (
    .A_N(m_ready),
    .B(stage1_valid),
    .Y(s_ready)
  );
  sky130_fd_sc_hd__dfrtp_1 _33_ (
    .CLK(clk),
    .D(_00_),
    .Q(stage1_data[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _34_ (
    .CLK(clk),
    .D(_01_),
    .Q(stage1_data[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _35_ (
    .CLK(clk),
    .D(_02_),
    .Q(stage2_data[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _36_ (
    .CLK(clk),
    .D(_03_),
    .Q(stage2_data[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _37_ (
    .CLK(clk),
    .D(_04_),
    .Q(stage2_data[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _38_ (
    .CLK(clk),
    .D(_05_),
    .Q(stage2_data[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _39_ (
    .CLK(clk),
    .D(_06_),
    .Q(stage2_data[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _40_ (
    .CLK(clk),
    .D(_07_),
    .Q(stage2_data[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _41_ (
    .CLK(clk),
    .D(_08_),
    .Q(stage2_data[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _42_ (
    .CLK(clk),
    .D(_09_),
    .Q(stage2_data[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _43_ (
    .CLK(clk),
    .D(s_valid),
    .Q(stage1_valid),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _44_ (
    .CLK(clk),
    .D(stage1_valid),
    .Q(stage2_valid),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _45_ (
    .CLK(clk),
    .D(_10_),
    .Q(stage1_data[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _46_ (
    .CLK(clk),
    .D(_11_),
    .Q(stage1_data[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _47_ (
    .CLK(clk),
    .D(_12_),
    .Q(stage1_data[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _48_ (
    .CLK(clk),
    .D(_13_),
    .Q(stage1_data[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _49_ (
    .CLK(clk),
    .D(_14_),
    .Q(stage1_data[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _50_ (
    .CLK(clk),
    .D(_15_),
    .Q(stage1_data[5]),
    .RESET_B(rst_n)
  );
  assign m_data = stage2_data;
  assign m_valid = stage2_valid;
endmodule
