# Auto-generated by SiliconSignoffVerifier [config_hash: a07985c7b6d8cbb6]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog fifo_02_netlist.v
link_design fifo_02
read_sdc fifo_02.sdc
report_checks
report_wns
