/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_05(clk, rst_n, kick, fault);
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  input clk;
  wire clk;
  wire [2:0] counter;
  output fault;
  wire fault;
  wire fault_reg;
  input kick;
  wire kick;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__clkinv_1 _06_ (
    .A(counter[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a31o_1 _07_ (
    .A1(counter[0]),
    .A2(counter[2]),
    .A3(_02_),
    .B1(fault_reg),
    .X(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _08_ (
    .A(counter[0]),
    .B(kick),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__xnor2_1 _09_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _10_ (
    .A(kick),
    .B(_03_),
    .Y(_00_[1])
  );
  sky130_fd_sc_hd__nand3b_1 _11_ (
    .A_N(counter[2]),
    .B(counter[1]),
    .C(counter[0]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__a21bo_1 _12_ (
    .A1(counter[0]),
    .A2(counter[1]),
    .B1_N(counter[2]),
    .X(_05_)
  );
  sky130_fd_sc_hd__a21oi_1 _13_ (
    .A1(_04_),
    .A2(_05_),
    .B1(kick),
    .Y(_00_[2])
  );
  sky130_fd_sc_hd__dfrtp_1 _14_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(counter[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _15_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(counter[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _16_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(counter[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _17_ (
    .CLK(clk),
    .D(_01_),
    .Q(fault_reg),
    .RESET_B(rst_n)
  );
  assign fault = fault_reg;
endmodule
