"""Parameterized TCL Template Generator for Tier-1 Commercial EDA Toolchains.

Supports Synopsys (Design Compiler, Fusion Compiler, PrimeTime, Formality),
Cadence (Genus, Innovus, Tempus, Conformal), and Siemens (Calibre, Tessent).
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class SynthesisTCLConfig:
    """Configuration for commercial logic synthesis."""

    top_module: str
    verilog_sources: list[str]
    target_libraries: list[str]
    link_libraries: list[str]
    sdc_path: str
    clock_name: str = "clk"
    clock_period_ns: float = 1.0
    output_netlist_path: str = "netlist.v"
    output_sdc_path: str = "synth_out.sdc"
    report_dir: str = "reports"
    compile_ultra: bool = True
    clock_gating: bool = True
    retiming: bool = True


@dataclass(frozen=True)
class MCMMScenarioConfig:
    """Configuration for a single Multi-Corner Multi-Mode (MCMM) scenario."""

    name: str
    mode: str  # e.g., 'func', 'test', 'shift'
    corner: str  # e.g., 'ssgnp_0p675v_m40c', 'ffgnp_0p825v_125c', 'tt_0p750v_25c'
    liberty_paths: list[str]
    sdc_path: str
    temperature_c: float = 25.0
    voltage_v: float = 0.75
    parasitic_corner: str = "cworst"  # cworst, rcworst, cbest, rcbest, typical
    spef_path: str | None = None
    is_setup: bool = True
    is_hold: bool = True


@dataclass(frozen=True)
class PrimeTimeSTAConfig:
    """Configuration for Synopsys PrimeTime MCMM STA signoff."""

    top_module: str
    netlist_path: str
    scenarios: list[MCMMScenarioConfig]
    report_dir: str = "pt_reports"
    enable_si: bool = True
    enable_pocv: bool = True
    enable_lvf: bool = False
    max_transition_ps: float = 100.0
    clock_uncertainty_ps: float = 20.0


@dataclass(frozen=True)
class InnovusPnRConfig:
    """Configuration for Cadence Innovus nanometer place-and-route."""

    top_module: str
    netlist_path: str
    lef_paths: list[str]
    liberty_paths: list[str]
    sdc_path: str
    core_utilization: float = 0.65
    aspect_ratio: float = 1.0
    core_to_die_margin_um: float = 3.0
    output_gds_path: str = "design.gds"
    output_netlist_path: str = "pnr_netlist.v"
    report_dir: str = "innovus_reports"
    enable_cts: bool = True
    enable_opt: bool = True


@dataclass(frozen=True)
class CalibrePhysicalConfig:
    """Configuration for Siemens Calibre nmDRC / nmLVS / PERC verification."""

    top_module: str
    gds_path: str
    drc_rule_deck: str
    lvs_rule_deck: str
    schematic_netlist_path: str
    report_dir: str = "calibre_reports"
    drc_runset_path: str = "drc.runset"
    lvs_runset_path: str = "lvs.runset"
    num_cpus: int = 16


class CommercialTCLGenerator:
    """Generates hardened, production-grade TCL scripts for commercial EDA engines."""

    @staticmethod
    def generate_synopsys_dc(cfg: SynthesisTCLConfig) -> str:
        """Generate Synopsys Design Compiler (or Fusion Compiler) synthesis TCL."""
        target_libs = " ".join(f'"{lib}"' for lib in cfg.target_libraries)
        link_libs = " ".join(f'"{lib}"' for lib in cfg.link_libraries)
        src_files = " ".join(f'"{s}"' for s in cfg.verilog_sources)

        cg_cmd = "set_clock_gating_style -sequential_cell latch -positive_edge_logic {and} -control_point before" if cfg.clock_gating else "# Clock gating disabled"
        compile_cmd = "compile_ultra -gate_clock" if (cfg.compile_ultra and cfg.clock_gating) else ("compile_ultra" if cfg.compile_ultra else "compile")
        if cfg.retiming:
            compile_cmd += " -retime"

        return textwrap.dedent(f"""\
            # ══════════════════════════════════════════════════════════════════════════
            # Synopsys Design Compiler / Fusion Compiler Synthesis Script
            # Auto-generated by Mind 3.0 Commercial EDA Engine
            # ══════════════════════════════════════════════════════════════════════════
            set_host_options -max_cores 8
            set sh_enable_line_editing true

            set target_library [list {target_libs}]
            set synthetic_library [list dw_foundation.sldb]
            set link_library [list * {link_libs} $synthetic_library]

            file mkdir {cfg.report_dir}

            # 1. Read Design RTL
            analyze -format sverilog [list {src_files}]
            elaborate {cfg.top_module}
            current_design {cfg.top_module}
            link
            check_design > {cfg.report_dir}/check_design.rpt

            # 2. Timing Constraints
            if {{[file exists "{cfg.sdc_path}"]}} {{
                read_sdc "{cfg.sdc_path}"
            }} else {{
                create_clock -name {cfg.clock_name} -period {cfg.clock_period_ns} [get_ports {cfg.clock_name}]
                set_input_delay -clock {cfg.clock_name} [expr {cfg.clock_period_ns} * 0.2] [all_inputs]
                set_output_delay -clock {cfg.clock_name} [expr {cfg.clock_period_ns} * 0.2] [all_outputs]
            }}

            # 3. Optimization Constraints & Clock Gating
            {cg_cmd}
            set_fix_multiple_port_nets -all -buffer_constants
            set_critical_range 0.5 [current_design]

            # 4. Compile & Retime
            {compile_cmd}

            # 5. Export Reports & Synthesized Gate-Level Netlist
            report_qor > {cfg.report_dir}/qor.rpt
            report_timing -delay_type max -max_paths 50 > {cfg.report_dir}/timing_setup.rpt
            report_timing -delay_type min -max_paths 50 > {cfg.report_dir}/timing_hold.rpt
            report_area -hierarchy > {cfg.report_dir}/area.rpt
            report_power -hierarchy > {cfg.report_dir}/power.rpt
            report_clock_gating > {cfg.report_dir}/clock_gating.rpt

            write -format verilog -hierarchy -output "{cfg.output_netlist_path}"
            write_sdc "{cfg.output_sdc_path}"

            puts "\\[MIND3_SYNTH_COMPLETE\\]"
            quit
        """)

    @staticmethod
    def generate_cadence_genus(cfg: SynthesisTCLConfig) -> str:
        """Generate Cadence Genus synthesis TCL."""
        target_libs = " ".join(f'"{lib}"' for lib in cfg.target_libraries)
        src_files = " ".join(f'"{s}"' for s in cfg.verilog_sources)

        return textwrap.dedent(f"""\
            # ══════════════════════════════════════════════════════════════════════════
            # Cadence Genus Synthesis Script
            # Auto-generated by Mind 3.0 Commercial EDA Engine
            # ══════════════════════════════════════════════════════════════════════════
            set_db max_cpus 8
            set_db init_lib_search_path [list .]
            set_db library [list {target_libs}]

            file mkdir {cfg.report_dir}

            read_hdl -language sv [list {src_files}]
            elaborate {cfg.top_module}
            init_design

            if {{[file exists "{cfg.sdc_path}"]}} {{
                read_sdc "{cfg.sdc_path}"
            }} else {{
                create_clock -name {cfg.clock_name} -period {cfg.clock_period_ns} [get_ports {cfg.clock_name}]
            }}

            syn_generic
            syn_map
            syn_opt

            report_timing > {cfg.report_dir}/timing.rpt
            report_area > {cfg.report_dir}/area.rpt
            report_power > {cfg.report_dir}/power.rpt
            report_qor > {cfg.report_dir}/qor.rpt

            write_hdl > "{cfg.output_netlist_path}"
            write_sdc > "{cfg.output_sdc_path}"

            puts "\\[MIND3_SYNTH_COMPLETE\\]"
            exit
        """)

    @staticmethod
    def generate_primetime_mcmm(cfg: PrimeTimeSTAConfig) -> str:
        """Generate Synopsys PrimeTime Multi-Corner Multi-Mode (MCMM) STA script."""
        scenario_blocks: list[str] = []
        for sc in cfg.scenarios:
            libs = " ".join(f'"{lib}"' for lib in sc.liberty_paths)
            spef_cmd = f'read_parasitics -format spef "{sc.spef_path}"' if sc.spef_path else "# No SPEF parasitics specified"
            scenario_blocks.append(textwrap.dedent(f"""\
                # ── Scenario: {sc.name} ({sc.mode} / {sc.corner}) ──
                create_scenario {sc.name}
                set_operating_conditions -temperature {sc.temperature_c} -voltage {sc.voltage_v}
                set_target_library [list {libs}]
                set_link_library [list * {libs}]
                read_sdc "{sc.sdc_path}"
                {spef_cmd}
                set_scenario_options -scenarios [list {sc.name}] -setup {str(sc.is_setup).lower()} -hold {str(sc.is_hold).lower()}
            """))

        si_cmd = "set_app_var si_enable_analysis true\nset_app_var si_xtalk_composite_aggressor_mode true" if cfg.enable_si else "# SI analysis disabled"
        pocv_cmd = "set_app_var timing_pocv_enable_analysis true\nset_app_var timing_pocv_filter_mode standard" if cfg.enable_pocv else "# POCV disabled"

        return textwrap.dedent(f"""\
            # ══════════════════════════════════════════════════════════════════════════
            # Synopsys PrimeTime Multi-Corner Multi-Mode (MCMM) Signoff STA
            # Auto-generated by Mind 3.0 Commercial EDA Engine
            # ══════════════════════════════════════════════════════════════════════════
            set_host_options -max_cores 16
            set sh_enable_line_editing true

            {si_cmd}
            {pocv_cmd}

            file mkdir {cfg.report_dir}

            # Read Netlist
            read_verilog "{cfg.netlist_path}"
            current_design {cfg.top_module}
            link

            # Configure MCMM Scenarios
            {"".join(scenario_blocks)}

            # Perform Full Timing Update
            check_timing > {cfg.report_dir}/check_timing.rpt
            update_timing -full

            # Generate Global Signoff Reports Across All Scenarios
            report_global_timing > {cfg.report_dir}/global_timing.rpt
            report_timing -delay_type max -slack_lesser_than 0.0 -max_paths 100 > {cfg.report_dir}/setup_violations.rpt
            report_timing -delay_type min -slack_lesser_than 0.0 -max_paths 100 > {cfg.report_dir}/hold_violations.rpt
            report_analysis_coverage > {cfg.report_dir}/coverage.rpt
            report_bottleneck -max_cells 20 > {cfg.report_dir}/bottlenecks.rpt

            # Summary Metrics for Mind 3.0 Parser
            puts "\\[MIND3_PT_SUMMARY\\]"
            foreach_in_collection sc [all_scenarios] {{
                current_scenario $sc
                set sc_name [get_object_name $sc]
                set setup_wns [get_attribute [get_timing_paths -delay_type max -max_paths 1] slack]
                set hold_wns  [get_attribute [get_timing_paths -delay_type min -max_paths 1] slack]
                puts "SCENARIO: $sc_name | SETUP_WNS: $setup_wns | HOLD_WNS: $hold_wns"
            }}
            puts "\\[MIND3_PT_COMPLETE\\]"
            quit
        """)

    @staticmethod
    def generate_cadence_innovus_pnr(cfg: InnovusPnRConfig) -> str:
        """Generate Cadence Innovus nanometer PnR script with CTS and routing."""
        lef_list = " ".join(f'"{lef}"' for lef in cfg.lef_paths)
        lib_list = " ".join(f'"{lib}"' for lib in cfg.liberty_paths)

        return textwrap.dedent(f"""\
            # ══════════════════════════════════════════════════════════════════════════
            # Cadence Innovus Nanometer Place-and-Route Script
            # Auto-generated by Mind 3.0 Commercial EDA Engine
            # ══════════════════════════════════════════════════════════════════════════
            setMultiCpuUsage -localCpu 16
            file mkdir {cfg.report_dir}

            set init_verilog "{cfg.netlist_path}"
            set init_top_cell "{cfg.top_module}"
            set init_lef_file [list {lef_list}]
            set init_mmmc_file "mccm.view"

            init_design

            # Floorplanning
            floorPlan -r {cfg.aspect_ratio} {cfg.core_utilization} \\
                      {cfg.core_to_die_margin_um} {cfg.core_to_die_margin_um} \\
                      {cfg.core_to_die_margin_um} {cfg.core_to_die_margin_um}

            # Standard Cell Placement
            setPlaceMode -prerouteResourceBudget true
            place_opt_design -out_dir {cfg.report_dir}/place_opt

            # Clock Tree Synthesis (CCOpt)
            create_ccopt_clock_tree_spec
            ccopt_design -out_dir {cfg.report_dir}/cts

            # Nanometer Routing
            setNanoRouteMode -quiet -routeWithSiDriven true
            setNanoRouteMode -quiet -routeWithTimingDriven true
            routeDesign -out_dir {cfg.report_dir}/route

            # Post-Route Optimization
            optDesign -postRoute -outDir {cfg.report_dir}/post_route_opt

            # Physical Verification Checks
            verify_drc -report {cfg.report_dir}/drc.rpt
            verify_connectivity -report {cfg.report_dir}/conn.rpt
            verify_process_antenna -report {cfg.report_dir}/antenna.rpt

            # Export GDS and Netlist
            saveNetlist "{cfg.output_netlist_path}"
            streamOut "{cfg.output_gds_path}" -merge [list {lef_list}] -mapFile gds.map

            puts "\\[MIND3_INNOVUS_COMPLETE\\]"
            exit
        """)

    @staticmethod
    def generate_calibre_runset(cfg: CalibrePhysicalConfig) -> dict[str, str]:
        """Generate Calibre nmDRC and nmLVS runset control files."""
        drc_runset = textwrap.dedent(f"""\
            *drcRulesFile: {cfg.drc_rule_deck}
            *drcRunDir: {cfg.report_dir}/drc
            *drcLayoutPaths: {cfg.gds_path}
            *drcLayoutPrimary: {cfg.top_module}
            *drcLayoutFormat: GDSII
            *drcResultsFile: {cfg.report_dir}/drc/calibre_drc.summary
            *drcSummaryFile: {cfg.report_dir}/drc/drc.sum
            *cmnFDICases: 1
            *cmnNumCPUs: {cfg.num_cpus}
            *cmnViewSummary: 0
        """)

        lvs_runset = textwrap.dedent(f"""\
            *lvsRulesFile: {cfg.lvs_rule_deck}
            *lvsRunDir: {cfg.report_dir}/lvs
            *lvsLayoutPaths: {cfg.gds_path}
            *lvsLayoutPrimary: {cfg.top_module}
            *lvsLayoutFormat: GDSII
            *lvsSourcePath: {cfg.schematic_netlist_path}
            *lvsSourcePrimary: {cfg.top_module}
            *lvsSourceFormat: SPICE
            *lvsReportFile: {cfg.report_dir}/lvs/calibre_lvs.report
            *lvsSummaryFile: {cfg.report_dir}/lvs/lvs.sum
            *cmnNumCPUs: {cfg.num_cpus}
        """)

        return {
            cfg.drc_runset_path: drc_runset,
            cfg.lvs_runset_path: lvs_runset,
        }
