/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module fsm_heldout_04(clk, rst_n, din, dout, stuffed);
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  input clk;
  wire clk;
  wire [2:0] count;
  input din;
  wire din;
  output dout;
  wire dout;
  input rst_n;
  wire rst_n;
  wire state;
  output stuffed;
  wire stuffed;
  sky130_fd_sc_hd__o21a_1 _04_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(count[2]),
    .X(_02_)
  );
  sky130_fd_sc_hd__o21a_1 _05_ (
    .A1(state),
    .A2(_02_),
    .B1(din),
    .X(_01_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _06_ (
    .A(din),
    .SLEEP(state),
    .X(dout)
  );
  sky130_fd_sc_hd__nor3b_1 _07_ (
    .A(count[0]),
    .B(_02_),
    .C_N(din),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__a21oi_1 _08_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(count[2]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__o211a_1 _09_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(_03_),
    .C1(din),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__nor3b_1 _10_ (
    .A(_02_),
    .B(_03_),
    .C_N(din),
    .Y(_00_[2])
  );
  sky130_fd_sc_hd__dfrtp_1 _11_ (
    .CLK(clk),
    .D(_01_),
    .Q(state),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _12_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(count[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _13_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(count[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _14_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(count[2]),
    .RESET_B(rst_n)
  );
  assign stuffed = state;
endmodule
