# Auto-generated by SiliconSignoffVerifier [config_hash: c94f439859255401]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog fsm_heldout_04_netlist.v
link_design fsm_heldout_04
read_sdc fsm_heldout_04.sdc
report_checks
report_wns
