/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_07(clk, rst_n, clear, en, count, max_pulse);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  input clear;
  wire clear;
  input clk;
  wire clk;
  output [7:0] count;
  wire [7:0] count;
  wire [7:0] count_reg;
  input en;
  wire en;
  output max_pulse;
  wire max_pulse;
  wire max_pulse_reg;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__a21oi_1 _22_ (
    .A1(count_reg[0]),
    .A2(en),
    .B1(clear),
    .Y(_09_)
  );
  sky130_fd_sc_hd__o21a_1 _23_ (
    .A1(count_reg[0]),
    .A2(en),
    .B1(_09_),
    .X(_01_)
  );
  sky130_fd_sc_hd__and3_1 _24_ (
    .A(count_reg[0]),
    .B(count_reg[1]),
    .C(en),
    .X(_10_)
  );
  sky130_fd_sc_hd__a21oi_1 _25_ (
    .A1(count_reg[0]),
    .A2(en),
    .B1(count_reg[1]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor3_1 _26_ (
    .A(clear),
    .B(_10_),
    .C(_11_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _27_ (
    .A(count_reg[2]),
    .B(_10_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__and4_1 _28_ (
    .A(count_reg[0]),
    .B(count_reg[1]),
    .C(count_reg[2]),
    .D(en),
    .X(_13_)
  );
  sky130_fd_sc_hd__nor3_1 _29_ (
    .A(clear),
    .B(_12_),
    .C(_13_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__and2_0 _30_ (
    .A(count_reg[3]),
    .B(_13_),
    .X(_14_)
  );
  sky130_fd_sc_hd__nor2_1 _31_ (
    .A(count_reg[3]),
    .B(_13_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor3_1 _32_ (
    .A(clear),
    .B(_14_),
    .C(_15_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _33_ (
    .A(count_reg[4]),
    .B(_14_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor2_1 _34_ (
    .A(clear),
    .B(_16_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__and4_1 _35_ (
    .A(count_reg[3]),
    .B(count_reg[4]),
    .C(count_reg[5]),
    .D(_13_),
    .X(_17_)
  );
  sky130_fd_sc_hd__a21oi_1 _36_ (
    .A1(count_reg[4]),
    .A2(_14_),
    .B1(count_reg[5]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nor3_1 _37_ (
    .A(clear),
    .B(_17_),
    .C(_18_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(count_reg[6]),
    .B(_17_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nor2_1 _39_ (
    .A(clear),
    .B(_19_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__and3_1 _40_ (
    .A(count_reg[6]),
    .B(count_reg[7]),
    .C(_17_),
    .X(_20_)
  );
  sky130_fd_sc_hd__a21oi_1 _41_ (
    .A1(count_reg[6]),
    .A2(_17_),
    .B1(count_reg[7]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nor3_1 _42_ (
    .A(clear),
    .B(_20_),
    .C(_21_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _43_ (
    .A(_20_),
    .SLEEP(clear),
    .X(_00_)
  );
  sky130_fd_sc_hd__dfrtp_1 _44_ (
    .CLK(clk),
    .D(_01_),
    .Q(count_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _45_ (
    .CLK(clk),
    .D(_02_),
    .Q(count_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _46_ (
    .CLK(clk),
    .D(_03_),
    .Q(count_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _47_ (
    .CLK(clk),
    .D(_04_),
    .Q(count_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _48_ (
    .CLK(clk),
    .D(_05_),
    .Q(count_reg[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _49_ (
    .CLK(clk),
    .D(_06_),
    .Q(count_reg[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _50_ (
    .CLK(clk),
    .D(_07_),
    .Q(count_reg[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _51_ (
    .CLK(clk),
    .D(_08_),
    .Q(count_reg[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _52_ (
    .CLK(clk),
    .D(_00_),
    .Q(max_pulse_reg),
    .RESET_B(rst_n)
  );
  assign count = count_reg;
  assign max_pulse = max_pulse_reg;
endmodule
