# Auto-generated by SiliconSignoffVerifier [config_hash: 7e2a9ed3744f38d9]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog counter_07_netlist.v
link_design counter_07
read_sdc counter_07.sdc
report_checks
report_wns
