/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module fifo_06(clk, rst_n, valid_in, ready_out, valid_out, ready_in);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  input clk;
  wire clk;
  wire empty;
  wire full;
  input ready_in;
  wire ready_in;
  output ready_out;
  wire ready_out;
  wire ready_out_reg;
  input rst_n;
  wire rst_n;
  input valid_in;
  wire valid_in;
  output valid_out;
  wire valid_out;
  wire valid_out_reg;
  sky130_fd_sc_hd__clkinv_1 _09_ (
    .A(empty),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _10_ (
    .A(valid_out_reg),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2_1 _11_ (
    .A(valid_out_reg),
    .B(ready_in),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand2b_1 _12_ (
    .A_N(full),
    .B(valid_in),
    .Y(_06_)
  );
  sky130_fd_sc_hd__a21o_1 _13_ (
    .A1(valid_in),
    .A2(_05_),
    .B1(full),
    .X(_02_)
  );
  sky130_fd_sc_hd__nand3_1 _14_ (
    .A(valid_out_reg),
    .B(ready_in),
    .C(valid_in),
    .Y(_07_)
  );
  sky130_fd_sc_hd__mux2i_1 _15_ (
    .A0(ready_in),
    .A1(_07_),
    .S(_06_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _16_ (
    .A(_00_),
    .B(_08_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__o21ai_0 _17_ (
    .A1(_04_),
    .A2(ready_in),
    .B1(_06_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__dfrtp_1 _18_ (
    .CLK(clk),
    .D(_02_),
    .Q(full),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _19_ (
    .CLK(clk),
    .D(_03_),
    .Q(empty),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _20_ (
    .CLK(clk),
    .D(_01_),
    .Q(valid_out_reg),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _21_ (
    .CLK(clk),
    .D(_00_),
    .Q(ready_out_reg),
    .SET_B(rst_n)
  );
  assign ready_out = ready_out_reg;
  assign valid_out = valid_out_reg;
endmodule
