# Auto-generated by SiliconSignoffVerifier [config_hash: ae8a0234bdbc6eaa]
read_liberty /home/mind/pdk/sky130A/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog fifo_06_netlist.v
link_design fifo_06
read_sdc fifo_06.sdc
report_checks
report_wns
