/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_05(clk, rst_n, kick, fault);
  wire _0_;
  input clk;
  wire clk;
  output fault;
  wire fault;
  wire fault_reg;
  input kick;
  wire kick;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__clkinv_1 _1_ (
    .A(kick),
    .Y(_0_)
  );
  sky130_fd_sc_hd__dfrtp_1 _2_ (
    .CLK(clk),
    .D(_0_),
    .Q(fault_reg),
    .RESET_B(rst_n)
  );
  assign fault = fault_reg;
endmodule
