/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_02(clk, rst_n, en, gray);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input clk;
  wire clk;
  input en;
  wire en;
  output [3:0] gray;
  wire [3:0] gray;
  wire [3:0] gray_reg;
  wire [3:0] \next_gray$func$counter_02.sv:14$1.current_gray ;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__nand2_1 _08_ (
    .A(en),
    .B(gray_reg[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _09_ (
    .A(gray_reg[0]),
    .B(_04_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nand2b_1 _10_ (
    .A_N(en),
    .B(gray_reg[1]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__o21ai_0 _11_ (
    .A1(gray_reg[2]),
    .A2(gray_reg[3]),
    .B1(en),
    .Y(_06_)
  );
  sky130_fd_sc_hd__and3_1 _12_ (
    .A(en),
    .B(gray_reg[2]),
    .C(gray_reg[3]),
    .X(_07_)
  );
  sky130_fd_sc_hd__a21oi_1 _13_ (
    .A1(_05_),
    .A2(_06_),
    .B1(_07_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _14_ (
    .A0(gray_reg[2]),
    .A1(gray_reg[3]),
    .S(en),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _15_ (
    .A0(gray_reg[3]),
    .A1(gray_reg[2]),
    .S(en),
    .X(_03_)
  );
  sky130_fd_sc_hd__dfrtp_1 _16_ (
    .CLK(clk),
    .D(_00_),
    .Q(gray_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _17_ (
    .CLK(clk),
    .D(_01_),
    .Q(gray_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _18_ (
    .CLK(clk),
    .D(_02_),
    .Q(gray_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _19_ (
    .CLK(clk),
    .D(_03_),
    .Q(gray_reg[3]),
    .RESET_B(rst_n)
  );
  assign gray = gray_reg;
  assign \next_gray$func$counter_02.sv:14$1.current_gray  = 4'hx;
endmodule
